### ISSUE TITLE
Is training WaveODE with 2-Rectified Flow required?

### ISSUE THREAD

**Issue by egorsmkv** [WelkinYang/WaveODE#3]

**Comment by egorsmkv** [comment]
I just integrated WaveODE with RAD-TTS

The source code for it: https://github.com/egorsmkv/radtts-waveode

@WelkinYang how much epochs we need to train to get intelligible results from acoustic models?

**Comment by WelkinYang** [comment]
2-Rectified Flow has better performance with small sampling steps than 1-Rectified Flow, and the topline performance of 2-Rectified Flow is the RK45 results of 1-Rectified Flow（Because we train the 2-Rectified Flow using the data generated from  the RK45 results of 1-Rectified Flow ）.
And the results  depend on your dataset（more epochs are better empirically） and welcome share your results.

**Comment by egorsmkv** [comment]
Thank you, @WelkinYang !

At the moment I integrated two codebases but the results are noise, I guess my dataset preparation is incorrect (I have used librosa to get MELs instead of Torch itself). Going to retry in a few days. I will share my results.

**Comment by egorsmkv** [comment]
@WelkinYang hello

My curiosity in this project won and I have results earlier. I have changed the format I have used to generate MEL spectrograms (look in this issue: https://github.com/egorsmkv/radtts-waveode/issues/1) and it helped.


https://user-images.githubusercontent.com/7875085/235501796-76378b8a-23fe-4cfb-829e-04c8312de273.mp4

Above is synthesized speech with the following text in Ukrainian: 

> Мене звати Лада, я комп'ютерний голос, який ти чуєш зараз, тому не думай, що я існую.
> My name is Lada, I'm the computer voice you're hearing now, so don't think I exist.

So I can constant that https://github.com/egorsmkv/radtts-waveode works well now.

**Comment by egorsmkv** [comment]
I am continuing to train a 1-Rectified Flow model, after 500 epochs I will start to train a 2-Rectified Flow model.

**Comment by egorsmkv** [comment]
![image](https://user-images.githubusercontent.com/7875085/235740775-3a70eef5-156a-442c-909e-239bfb55e25d.png)

Okay, it does not much differ on 150 epoch so I will start training a 2-Rectified Flow model from this epoch

**Comment by egorsmkv** [comment]
@WelkinYang what was your RTF when you're using RK45? It takes about 50 seconds for each file on my dataset, is it normal?

**Comment by egorsmkv** [comment]
@WelkinYang hi, can you, please, look on the question above?

**Comment by egorsmkv** [comment]
Any update?
